flowchart TB
    n1((24)) --> B[/"Ler nome_categoria"/]
    n5["Buscar\nCategoria\nde Produto"]
    B --> C["Preparar e\n executar SELECT SQL"]
    C --> D{"Preparou e\n executou \ncom sucesso?"}
    D -- Não --> n2["Imprime Erro"]
    D -- Sim --> n3["Imprimir\n Resultados"]
    n2 --> n4((26))
    n3 --> n4

    n2@{ shape: doc}
    n3@{ shape: doc}
    n5@{ shape: comment}