flowchart TB
    n1((58)) --> B[Preparar e executar SELECT SQL de todas as formas de pagamento]
    n5["Listar\nFormas de\nPagamento"]
    B --> C{"Preparou e\n executou \ncom sucesso?"}
    C -- Não --> n2["Imprime Erro"]
    C -- Sim --> n3["Imprimir\n Resultados"]
    n2 --> n4((59))
    n3 --> n4

    n2@{ shape: doc}
    n3@{ shape: doc}
    n5@{ shape: comment}
