flowchart TB
    n1((41)) --> B[/"Ler nome do\ngato"/]
    n50["Cadastrar\nGato"]
    B --> C{"Nome >=\n3 letras?"}
    C -- Não --> B
    C -- Sim --> D[/"Ler personalidade e status"/]
    D --> n2["Imprime opções\nde playground:\n 1-Buscar\n 2-Listar\n 3-Cadastrar"]
    n2 --> F[/"Ler Opção"/]
    F --> G{"Opção?"}
    G -- "1 - Buscar" --> n3((39))
    G -- "2 - Listar" --> n4((40))
    G -- "3 - Cadastrar" --> n5((37))
    G -- Outra --> n6["Erro:\nOpção\nInválida"]
    n3 --> M{"id_play == 0?"}
    n4 --> M
    n5 --> M
    n6 --> n2
    M -- Sim --> n2
    M -- Não --> N["id_playground = id_play"]
    N --> O["Preparar e\nexecutar INSERT SQL"]
    O --> P{"Executou com\nsucesso?"}
    P -- Não --> n8["Imprime erro"]
    P -- Sim --> Q["Obter ID gerado"]
    Q --> n9["Imprime sucesso"]
    n8 --> R(["Retornar 0"])
    n9 --> S(["Retornar ID"])
    R --> n10((50))
    S --> n10

    n50@{ shape: comment}
    n2@{ shape: doc}
    n6@{ shape: doc}
    n8@{ shape: doc}
    n9@{ shape: doc}