flowchart TB
    n1(("6")) --> n2[Imprimir Cabeçalho OUTROS]
    n2 --> n3[Mostrar Opções de Outros]
    n3 --> D[/Ler Opção/]
    D --> E{Opção?}
    E -- "1 - Cadastrar\n Funcionário" --> n6(("51"))
    E -- "2 - Editar\n Funcionário" --> n7(("52"))
    E -- "3 - Buscar\n Funcionário" --> n8(("53"))
    E -- "4 - Listar\n Funcionários" --> n9(("54"))
    E -- "1 - Cadastrar\n Forma de\n Pagamento" --> n10(("55"))
    E -- "2 - Editar\n Forma de\n Pagamento" --> n11(("56"))
    E -- "3 - Buscar\n Forma de\n Pagamento" --> n12(("57"))
    E -- "4 - Listar\n Formas de \nPagamento" --> n13(("58"))
    E -- "0 - Voltar" --> n4(("8"))
    E -- Outra --> n5["Exibir\n Opção Inválida"]
    n5 --> n2
    n14((59)) --> n2
    n2@{ shape: doc}
    n3@{ shape: doc}
    n5@{ shape: doc}