flowchart TB
    n1((46)) --> n12[Imprime opções:\n 1-Buscar por playground\n 2-Listar\n 3-Cadastrar]
    n5["Editar\nSessão de\nPlayground"]
    n12 --> C[/Ler Opção/]
    C --> D{Opção?}
    D -- "1 - Buscar" --> n2((48))
    D -- "2 - Listar" --> n3((49))
    D -- "3 - Cadastrar" --> n4((45))
    D -- Outra --> n11[Erro:\nOpção\nInválida]
    n2 --> H
    n3 --> H
    n4 --> F{Nova\nsessão\ncriada?}
    n11 --> n12
    F -- Sim --> n6[/Deseja usar a\nnova sessão? s/n/]
    F -- Não --> H
    n6 --> I{Resposta?}
    I -- s --> G[id_sessao =\n id_nova_sessao]
    I -- n --> H[/Ler ID da sessão/]
    H --> J{id_sessao == 0?}
    J -- Sim --> n12
    J -- Não --> K[/Ler novos dados e Validar/]
    G --> K
    K --> L{Tudo igual\na -1?}
    L -- Sim --> n7[Imprime que\nnada foi alterado]
    L -- Não --> M[Preparar e\nexecutar SQL UPDATE]
    M --> N{"Preparou e\nexecutou\ncom sucesso?"}
    N -- Não --> n8["Imprime Erro"]
    N -- Sim --> n9["Imprimir\nSucesso"]

    n7 --> n10((50))
    n8 --> n10
    n9 --> n10

    n6@{ shape: doc}
    n7@{ shape: doc}
    n8@{ shape: doc}
    n9@{ shape: doc}
    n11@{ shape: doc}
    n12@{ shape: doc}
    n5@{ shape: comment}